"""Initial migration: create all tables

Revision ID: b693db37cc5a
Revises:
Create Date: 2026-07-16 11:27:41.826521

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b693db37cc5a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_tax_deductible", sa.Boolean(), nullable=False),
        sa.Column("tax_category", sa.String(length=50), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "code", name="uq_category_parent_code"),
    )
    op.create_index(op.f("ix_categories_code"), "categories", ["code"], unique=True)
    op.create_index(op.f("ix_categories_is_active"), "categories", ["is_active"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_index(
        "ix_categories_parent_active", "categories", ["parent_id", "is_active"], unique=False
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_is_active"), "tags", ["is_active"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)
    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("image_hash", sa.String(length=64), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column("ocr_language", sa.String(length=20), nullable=False),
        sa.Column("receipt_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("store_name", sa.String(length=255), nullable=True),
        sa.Column("total_amount", sa.Integer(), nullable=True),
        sa.Column("tax_amount", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("category_confidence", sa.Float(), nullable=True),
        sa.Column("ai_comment", sa.Text(), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UNPARSED",
                "PARSING",
                "UNAPPROVED",
                "APPROVED",
                "REJECTED",
                "FAILED",
                name="receiptstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename", name="uq_receipts_stored_filename"),
    )
    op.create_index(op.f("ix_receipts_category_id"), "receipts", ["category_id"], unique=False)
    op.create_index(
        "ix_receipts_date_store_amount",
        "receipts",
        ["receipt_date", "store_name", "total_amount"],
        unique=False,
    )
    op.create_index("ix_receipts_hash_status", "receipts", ["image_hash", "status"], unique=False)
    op.create_index(op.f("ix_receipts_image_hash"), "receipts", ["image_hash"], unique=False)
    op.create_index(op.f("ix_receipts_receipt_date"), "receipts", ["receipt_date"], unique=False)
    op.create_index(op.f("ix_receipts_status"), "receipts", ["status"], unique=False)
    op.create_index("ix_receipts_status_date", "receipts", ["status", "receipt_date"], unique=False)
    op.create_index(op.f("ix_receipts_store_name"), "receipts", ["store_name"], unique=False)
    op.create_index(
        op.f("ix_receipts_stored_filename"), "receipts", ["stored_filename"], unique=True
    )
    op.create_index(op.f("ix_receipts_total_amount"), "receipts", ["total_amount"], unique=False)
    op.create_table(
        "duplicate_checks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_receipt_id", sa.Integer(), nullable=False),
        sa.Column("target_receipt_id", sa.Integer(), nullable=False),
        sa.Column("store_name_score", sa.Float(), nullable=True),
        sa.Column("amount_score", sa.Float(), nullable=True),
        sa.Column("date_score", sa.Float(), nullable=True),
        sa.Column("metadata_score", sa.Float(), nullable=True),
        sa.Column("image_hash_score", sa.Float(), nullable=True),
        sa.Column("ocr_similarity_score", sa.Float(), nullable=True),
        sa.Column("composite_score", sa.Float(), nullable=True),
        sa.Column("duplicate_threshold", sa.Float(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "NO_DUPLICATES",
                "HAS_DUPLICATES",
                "USER_REVIEWED",
                "FAILED",
                name="duplicatecheckstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("user_confirmed", sa.Boolean(), nullable=True),
        sa.Column("user_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_note", sa.Text(), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_receipt_id", "target_receipt_id", name="uq_duplicate_check_pair"
        ),
    )
    op.create_index(
        op.f("ix_duplicate_checks_composite_score"),
        "duplicate_checks",
        ["composite_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_checks_is_duplicate"), "duplicate_checks", ["is_duplicate"], unique=False
    )
    op.create_index(
        op.f("ix_duplicate_checks_source_receipt_id"),
        "duplicate_checks",
        ["source_receipt_id"],
        unique=False,
    )
    op.create_index(
        "ix_duplicate_checks_source_status",
        "duplicate_checks",
        ["source_receipt_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_checks_status"), "duplicate_checks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_duplicate_checks_target_receipt_id"),
        "duplicate_checks",
        ["target_receipt_id"],
        unique=False,
    )
    op.create_index(
        "ix_duplicate_checks_user_review",
        "duplicate_checks",
        ["user_confirmed", "user_reviewed_at"],
        unique=False,
    )
    op.create_table(
        "receipt_tags",
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("receipt_id", "tag_id"),
    )
    op.create_table(
        "rejection_reasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("reason_code", sa.String(length=50), nullable=False),
        sa.Column("reason_category", sa.String(length=50), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("user_note", sa.Text(), nullable=True),
        sa.Column("ai_feedback", sa.Text(), nullable=True),
        sa.Column("is_for_ai_training", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rejection_reasons_is_for_ai_training"),
        "rejection_reasons",
        ["is_for_ai_training"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rejection_reasons_reason_category"),
        "rejection_reasons",
        ["reason_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rejection_reasons_reason_code"), "rejection_reasons", ["reason_code"], unique=False
    )
    op.create_index(
        op.f("ix_rejection_reasons_receipt_id"), "rejection_reasons", ["receipt_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rejection_reasons_receipt_id"), table_name="rejection_reasons")
    op.drop_index(op.f("ix_rejection_reasons_reason_code"), table_name="rejection_reasons")
    op.drop_index(op.f("ix_rejection_reasons_reason_category"), table_name="rejection_reasons")
    op.drop_index(op.f("ix_rejection_reasons_is_for_ai_training"), table_name="rejection_reasons")
    op.drop_table("rejection_reasons")
    op.drop_table("receipt_tags")
    op.drop_index("ix_duplicate_checks_user_review", table_name="duplicate_checks")
    op.drop_index(op.f("ix_duplicate_checks_target_receipt_id"), table_name="duplicate_checks")
    op.drop_index(op.f("ix_duplicate_checks_status"), table_name="duplicate_checks")
    op.drop_index("ix_duplicate_checks_source_status", table_name="duplicate_checks")
    op.drop_index(op.f("ix_duplicate_checks_source_receipt_id"), table_name="duplicate_checks")
    op.drop_index(op.f("ix_duplicate_checks_is_duplicate"), table_name="duplicate_checks")
    op.drop_index(op.f("ix_duplicate_checks_composite_score"), table_name="duplicate_checks")
    op.drop_table("duplicate_checks")
    op.drop_index(op.f("ix_receipts_total_amount"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_stored_filename"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_store_name"), table_name="receipts")
    op.drop_index("ix_receipts_status_date", table_name="receipts")
    op.drop_index(op.f("ix_receipts_status"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_receipt_date"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_image_hash"), table_name="receipts")
    op.drop_index("ix_receipts_hash_status", table_name="receipts")
    op.drop_index("ix_receipts_date_store_amount", table_name="receipts")
    op.drop_index(op.f("ix_receipts_category_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_is_active"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index("ix_categories_parent_active", table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_is_active"), table_name="categories")
    op.drop_index(op.f("ix_categories_code"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
